spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: AshokIT@123
    url: jdbc:mysql://localhost:3306/sbms
    username: ashokit
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
